### ISSUE TITLE
For 100% Checklist:

### ISSUE THREAD

**Issue by JonSno29** [JonSno29/Number_1_Coders#17]
This project will be a centerpiece for your portfolio and your first opportunity to show employers your collaborative skills and coding abilities.

- [x] Use Bulma.
- [x] Deploys to GitHub pages(Works so far).
- [x] Responsive to user input.
- [x] Two server side API's.
- [x] Uses Modals.
- [x] Uses client-side storage.
- [x] Good file structure/Quality comments and Commits.
- [x] Responsive.
- [x] A kick ass README.
- [x] Be very descriptive on "COMMITS".
- [x] Add Project#1 to your portfolio.

**__PRESENTATION__**

- [x] Elevator pitch(One minute).
- [x] Explain project very, very well.
- [x] The User Story and motivation for development. 

 **__**The Project Process              PowerPoint**__**

- [x] Technologies used.
- [x] How were tasks delegated.
- [x] Challenge's.
- [x] Our Successes.
- [ ] Demo the project.
- [x] Directions for future development.
- [x] GitHub repository link.
- [x] Live Website link.
- [x] Why this project idea is unique and novel.

**__EACH MEMBER INDIVIDUALLY__**

- [x] Deployed URL of Number_1_Coders.
- [x] URL of Number_1_Coders GitHub repository. 
- [x] URL of YOUR portfolio with Project#1 added to it.

- [x] Dress nice...If you want. 
Pants not required.
